SUMMARY = "Intel® QuickAssist Technology(QAT) OpenSSL* Engine"

DESCRIPTION = "Intel® QuickAssist Technology OpenSSL* Engine (QAT_Engine) \
supports acceleration for both hardware as well as optimized software based on vectorized instructions."

HOMEPAGE = "https://github.com/intel/QAT_Engine"

SRC_URI = "git://github.com/intel/QAT_Engine.git;protocol=https;branch=master;"

SRCREV = "c1a7a965ce450afec74d490d0a6f7d382a1126aa"
